import { autoSchedule, createStandaloneCalendarItem, triggerAutomation } from './calendar-lib.js';
const DB='sm_content_os_v2';
const enums={funnel:['awareness','engagement','conversion','retention'],ideaStatus:['idea','selected','archived'],srcStatus:['draft','in_review','published']};
const defaultState={ideas:[],sources:[],repurposed:[],calendar:[],monthView:false,editingIdeaId:null,editingSourceId:null};
let state=JSON.parse(localStorage.getItem(DB)||'null')||defaultState;
const save=()=>localStorage.setItem(DB,JSON.stringify(state));
const id=(p)=>`${p}_${Math.random().toString(36).slice(2,10)}`;
const qs=(s)=>document.querySelector(s); const esc=(s='')=>s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const md=(t='')=>esc(t).replace(/^### (.*)$/gm,'<h4>$1</h4>').replace(/^## (.*)$/gm,'<h3>$1</h3>').replace(/^# (.*)$/gm,'<h2>$1</h2>').replace(/\*\*(.*?)\*\*/g,'<b>$1</b>').replace(/\*(.*?)\*/g,'<i>$1</i>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\n/g,'<br>');
const tagList=(s)=>[...new Set((s||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean))];
const err=(el,msg='')=>{el.textContent=msg;};
const validateIdea=(i)=> i.title.trim()&&i.description.trim()&&enums.funnel.includes(i.funnelStage)&&enums.ideaStatus.includes(i.status);
function renderIdeas(){
  const q=ideaSearch.value.toLowerCase(); const tag=ideaFilterTag.value.trim().toLowerCase(); ideas.innerHTML='';
  sourceIdea.innerHTML='<option value="">No linked idea</option>'+state.ideas.map(i=>`<option value="${i.id}">${esc(i.title)}</option>`).join('');
  state.ideas.filter(i=>(!q||(`${i.title} ${i.themeTags.join(',')}`).toLowerCase().includes(q))&&(!tag||i.themeTags.includes(tag))).forEach(i=>{const d=document.createElement('div'); d.className='item';
    d.innerHTML=`<b>${esc(i.title)}</b> <span class='tag'>${i.funnelStage}</span> <span class='tag'>${i.status}</span><div>${esc(i.description)}</div><div class='muted'>${i.themeTags.join(', ')}</div><div class='row'><button data-a='edit'>Edit</button><button data-a='del'>Delete</button></div>`;
    d.querySelector("[data-a='edit']").onclick=()=>{ideaId.value=i.id; ideaTitle.value=i.title; ideaDesc.value=i.description; ideaTags.value=i.themeTags.join(','); ideaFunnel.value=i.funnelStage; ideaPlatforms.value=i.platformPotential.join(','); ideaStatus.value=i.status; addIdea.textContent='Update Idea';};
    d.querySelector("[data-a='del']").onclick=()=>{state.ideas=state.ideas.filter(x=>x.id!==i.id); state.sources=state.sources.map(s=>s.ideaId===i.id?{...s,ideaId:undefined}:s); save(); renderAll();}; ideas.appendChild(d);}); }
function sourceCard(s){return `<b>${esc(s.title)}</b> (${s.format}) <span class='tag'>${s.status}</span><div class='muted'>Linked idea: ${s.ideaId||'none'}</div><div class='md'>${md((s.body||'').slice(0,220))}</div><div class='row'><button data-a='edit'>Edit</button><button data-a='draft'>Save draft</button><button data-a='review'>Submit review</button><button data-a='pub'>Publish</button><button data-a='gen'>Generate repurposed</button><button data-a='del'>Delete</button></div>`}
function regenerateFor(source){return ['linkedin','instagram','tiktok','youtube','newsletter'].map(p=>({id:id('rep'),sourceContentId:source.id,platform:p,format:p==='newsletter'?'email':'short_post',title:`${source.title} (${p})`,content:`${source.hook||''}\n\n${(source.body||'').slice(0,180)}\n\n#${p}`,hook:source.hook||'',cta:'Reply or DM for template',status:'draft'}));}
function renderSources(){sources.innerHTML=''; state.sources.forEach(s=>{const d=document.createElement('div'); d.className='item'; d.innerHTML=sourceCard(s);
  d.querySelector("[data-a='edit']").onclick=()=>{sourceId.value=s.id; sourceTitle.value=s.title; sourceFormat.value=s.format; sourceStatus.value=s.status; sourceIdea.value=s.ideaId||''; sourceBody.value=s.body||''; sourceHook.value=s.hook||''; sourceKeyPoints.value=(s.keyPoints||[]).join(','); sourceBody.dispatchEvent(new Event('input')); addSource.textContent='Update Source';};
  d.querySelector("[data-a='draft']").onclick=()=>updSourceStatus(s.id,'draft'); d.querySelector("[data-a='review']").onclick=()=>updSourceStatus(s.id,'in_review'); d.querySelector("[data-a='pub']").onclick=()=>updSourceStatus(s.id,'published');
  d.querySelector("[data-a='gen']").onclick=()=>{state.repurposed=state.repurposed.filter(r=>r.sourceContentId!==s.id).concat(regenerateFor(s)); save(); renderAll();};
  d.querySelector("[data-a='del']").onclick=()=>{state.sources=state.sources.filter(x=>x.id!==s.id); state.repurposed=state.repurposed.filter(r=>r.sourceContentId!==s.id); state.calendar=state.calendar.map(c=>(c.sourceContentId===s.id||c.repurposedContentId)&&!state.repurposed.find(r=>r.id===c.repurposedContentId)?{...c,detached:true,detachedReason:'Linked source/repurposed content deleted'}:c); save(); renderAll();};
  sources.appendChild(d);});}
const updSourceStatus=(idv,status)=>{state.sources=state.sources.map(s=>s.id===idv?{...s,status}:s); save(); renderSources();};
function renderRepurposed(){repurposed.innerHTML=''; state.repurposed.forEach(r=>{const d=document.createElement('div'); d.className='item'; d.innerHTML=`<b>${r.platform}</b> - ${esc(r.title)}<textarea>${esc(r.content)}</textarea><div class='row'><button class='copy'>Copy</button><button class='regen'>Regenerate</button><button class='sched'>Schedule</button></div>`;
 d.querySelector('textarea').onchange=(e)=>{r.content=e.target.value; save();}; d.querySelector('.copy').onclick=()=>navigator.clipboard.writeText(r.content); d.querySelector('.regen').onclick=()=>{const src=state.sources.find(s=>s.id===r.sourceContentId); if(!src)return; Object.assign(r,regenerateFor(src).find(x=>x.platform===r.platform)); save(); renderRepurposed();}; d.querySelector('.sched').onclick=()=>{state.calendar.push({id:id('cal'),repurposedContentId:r.id,sourceContentId:r.sourceContentId,contentType:'repurposed',platform:r.platform,title:r.title,content:r.content,publishDate:new Date().toISOString(),status:'draft',tags:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}); save(); renderCalendar();}; repurposed.appendChild(d);});}
function editCal(item){calEdit.style.display='block'; calId.value=item.id; calDate.value=item.publishDate.slice(0,10); calPlatform.value=item.platform; calContent.value=item.content||''; calCaption.value=item.caption||''; calTags.value=(item.tags||[]).join(',');}
function renderCalendar(){calendar.innerHTML=''; const byDate={}; state.calendar.forEach(i=>((byDate[i.publishDate.slice(0,10)]??=[]).push(i))); const makeItem=(item,c)=>{const el=document.createElement('div'); el.className='item'; const missingSrc=item.sourceContentId&&!state.sources.find(s=>s.id===item.sourceContentId); const missingRep=item.repurposedContentId&&!state.repurposed.find(r=>r.id===item.repurposedContentId); const detached=item.detached||missingSrc||missingRep;
 el.innerHTML=`${item.platform}: ${esc(item.title)} ${detached?"<span class='tag'>DETACHED</span>":''}<div class='row'><button data-a='edit'>edit</button><button data-a='copy'>copy content</button><button data-a='cap'>copy caption</button><button data-a='src' ${missingSrc?'disabled':''}>open source</button><button data-a='rep' ${missingRep?'disabled':''}>open repurposed</button><button data-a='auto'>send to automation</button></div>${detached?`<div class='muted'>${item.detachedReason||'Linked content removed'}</div>`:''}`;
 el.draggable=true; el.ondragstart=(e)=>e.dataTransfer.setData('text/plain',item.id); el.querySelector("[data-a='edit']").onclick=()=>editCal(item); el.querySelector("[data-a='copy']").onclick=()=>navigator.clipboard.writeText(item.content||''); el.querySelector("[data-a='cap']").onclick=()=>navigator.clipboard.writeText(item.caption||''); el.querySelector("[data-a='src']")?.addEventListener('click',()=>{const src=state.sources.find(s=>s.id===item.sourceContentId); if(src) alert(`Source: ${src.title}`)}); el.querySelector("[data-a='rep']")?.addEventListener('click',()=>{const rep=state.repurposed.find(r=>r.id===item.repurposedContentId); if(rep) alert(`Repurposed: ${rep.title}`)}); el.querySelector("[data-a='auto']").onclick=async()=>{await triggerAutomation(item.id,item.automationLink); alert('Automation triggered (or no webhook configured).');}; return el;};
 if(!state.monthView){const s=new Date((weekStart.value||new Date().toISOString().slice(0,10))+'T00:00:00Z'); const week=document.createElement('div'); week.className='week'; for(let d=0;d<7;d++){const c=new Date(s); c.setUTCDate(s.getUTCDate()+d); const key=c.toISOString().slice(0,10); const day=document.createElement('div'); day.className='day'; day.innerHTML=`<b>${key}</b>`; (byDate[key]||[]).forEach(item=>day.appendChild(makeItem(item,c))); day.ondragover=(e)=>e.preventDefault(); day.ondrop=(e)=>{const hit=state.calendar.find(x=>x.id===e.dataTransfer.getData('text/plain')); if(hit){hit.publishDate=c.toISOString();hit.updatedAt=new Date().toISOString();save();renderCalendar();}}; week.appendChild(day);} calendar.appendChild(week);} else {Object.entries(byDate).sort().forEach(([k,v])=>{const d=document.createElement('div'); d.className='item'; d.innerHTML=`<b>${k}</b> (${v.length})`; d.onclick=()=>{state.monthView=false; weekStart.value=k; renderCalendar();}; calendar.appendChild(d);});}}
function renderAll(){renderIdeas();renderSources();renderRepurposed();renderCalendar();}
addIdea.onclick=()=>{const obj={id:ideaId.value||id('idea'),title:ideaTitle.value.trim(),description:ideaDesc.value.trim(),themeTags:tagList(ideaTags.value),funnelStage:ideaFunnel.value,platformPotential:tagList(ideaPlatforms.value),status:ideaStatus.value,createdAt:new Date().toISOString()}; if(!validateIdea(obj)) return err(ideaErr,'Idea validation failed: title, description, funnel and status required.'); err(ideaErr,''); if(ideaId.value){state.ideas=state.ideas.map(i=>i.id===ideaId.value?{...i,...obj,createdAt:i.createdAt}:i);} else state.ideas.unshift(obj); ideaId.value=''; addIdea.textContent='Add Idea'; save(); renderAll();};
ideaSearch.oninput=renderIdeas; ideaFilterTag.oninput=renderIdeas;
sourceBody.oninput=()=>sourcePreview.innerHTML=md(sourceBody.value);
addSource.onclick=()=>{if(!sourceTitle.value.trim()||!sourceBody.value.trim()) return err(sourceErr,'Source title and markdown body are required.'); err(sourceErr,''); const obj={id:sourceId.value||id('src'),ideaId:sourceIdea.value||undefined,title:sourceTitle.value.trim(),format:sourceFormat.value,body:sourceBody.value,keyPoints:tagList(sourceKeyPoints.value),hook:sourceHook.value.trim(),status:sourceStatus.value}; if(!enums.srcStatus.includes(obj.status)) return; if(sourceId.value) state.sources=state.sources.map(s=>s.id===sourceId.value?{...s,...obj}:s); else state.sources.unshift(obj); sourceId.value=''; addSource.textContent='Save Source'; save(); renderAll();};
genRepurpose.onclick=()=>{const src=state.sources.find(s=>s.id===sourceIdea.value)||state.sources[0]; if(!src) return alert('Create source content first'); state.repurposed=state.repurposed.filter(r=>r.sourceContentId!==src.id).concat(regenerateFor(src)); save(); renderAll();};
autoScheduleBtn.onclick=()=>{const wk=(weekStart.value||new Date().toISOString().slice(0,10))+'T00:00:00Z'; const items=autoSchedule(state.repurposed.map(r=>({platform:r.platform,title:r.title,content:r.content,repurposedContentId:r.id,sourceContentId:r.sourceContentId,tags:[]})),wk,state.calendar); state.calendar=state.calendar.filter(i=>i.contentType!=='repurposed').concat(items); save(); renderCalendar();};
addStandalone.onclick=()=>{state.calendar.push(createStandaloneCalendarItem({title:standTitle.value,content:standContent.value,platform:standPlatform.value,publishDate:standDate.value||new Date().toISOString(),tags:tagList(standTags.value)})); save(); renderCalendar();};
monthView.onclick=()=>{state.monthView=!state.monthView; save(); renderCalendar();};
calCancel.onclick=()=>calEdit.style.display='none'; calSave.onclick=()=>{const it=state.calendar.find(c=>c.id===calId.value); if(!it)return; it.publishDate=new Date(calDate.value+'T00:00:00Z').toISOString(); it.platform=calPlatform.value; it.content=calContent.value; it.caption=calCaption.value; it.tags=tagList(calTags.value); it.updatedAt=new Date().toISOString(); calEdit.style.display='none'; save(); renderCalendar();};
renderAll();
